### ISSUE TITLE
Not even able to debug the application on emulators using Visual studio 2017.

### ISSUE THREAD

**Issue by krishnakumar-ViewLift** [Samsung/vs-tools-cps#1]
Not even able to debug the application on emulators using Visual studio 2017.

It's always throwing below error message in output window and terminate the debug:

=thread-selected,id="1"
Loaded '[vdso]'. Cannot find or open the symbol file.
Loaded 'linux-gate.so.1'. Cannot find or open the symbol file.
The thread 0x1 has exited with code 0 (0x0).
The program 'sdb.exe' has exited with code 0 (0x0).

![dotnet_debug_tv](https://user-images.githubusercontent.com/13046305/46814218-da3c3480-cd95-11e8-90af-048148d67100.png)

**Comment by MilanStarcevic** [comment]
I am having the exact same issue. I am using the following:
- Tizen.NET 4.0.0
- Visual Studio 2017, Version 15.8.7
- W-4.0-circle-x86-preview emulator

**Comment by winstone77** [comment]
Sorry for inconvenience on using Tizen extension.
We already knew this compatible issue with VS 15.8. We fixed our extension and our patch is under internal testing now.
It will be available on the begin of November at the Marketplace.

**Comment by MilanStarcevic** [comment]
Thank you for the update on the state of the patch. Looking forward to the release.

**Comment by tbpdev** [comment]
Any update on this @winstone77?
I'm using the VsExtention v2.3.0.0, with Tizen.Net 4.0 and a cross-platform wearable project.
But still getting the below and unable to debug within the wearable project:

![image](https://user-images.githubusercontent.com/46359665/50664975-eb689c00-0fa6-11e9-8ccf-8937060a9d27.png)

**Comment by tomh4** [comment]
Anyone figured this out ?

**Comment by js6pak** [comment]
Its started working for me when i installed stable version of .net core 2.0, **and unistalled all other versions.** There should be option to manual change net core version for project
